development:
    clients:
        default:
            uri: "mongodb+srv://guiddiel:<password>@dielproject.qmjdut5.mongodb.net/dielProject?retryWrites=true&w=majority"
            options:
                server_api:
                    version: "1"
